### ISSUE TITLE
Question: will you maintain the theme for grav 1.7

### ISSUE THREAD

**Issue by Japhys** [ParitoshBh/grav-coder#23]
I have been using it for quite a while and I still love it very much! Was wondering if the theme will work well with the upcoming 1.7 release and if you plan on making it fully compatible ( no idea if there are many changes). Hope so!

Regards!

**Comment by ParitoshBh** [comment]
For sure I intend to keep it updated and compatible. `1.7.0-rc.15` has been out for a month, I will try and test it against that. Thanks for bringing it up!

Will report here after testing.

**Comment by Japhys** [comment]
That is great news. Thanks so much

**Comment by Japhys** [comment]
@ParitoshBh I tested it with 1.7 and so far I am not seeing any problems apart from this one, but I guess it's a plugin issue

https://github.com/getgrav/grav-plugin-login/issues/269

**Comment by ParitoshBh** [comment]
Thanks for testing it out! I tried to upgrade my personal website to use `1.7.0-rc.20` and without any changes, the homepage looks like this,

![image](https://user-images.githubusercontent.com/11397869/103143885-88212880-46ed-11eb-8305-e9a8c3d99c52.png)

However, adding following to `/user/config/system.yaml` fixes the issues. Did you have to make a similar change?

```yaml
strict_mode:
  yaml_compat: true
  twig_compat: true
```

Also, for the issue you've tagged, it appears to be plugin related rather than theme. However, if there's something you need hand with let me know!

**Comment by Japhys** [comment]
Thanks. Very interesting. I did not encounter these problems. I started off with a clean grav installation and moved the user content to the new installation. Worked straight away

**Comment by ParitoshBh** [comment]
Pushed a new release `0.1.8`, supports Grav `1.7.0`, tested up-to RC20.
