### ISSUE TITLE
I need plugin - page on password

### ISSUE THREAD

**Issue by bialy03** [ParitoshBh/grav-coder#8]
For luck =), I need a plugin that will allow you to block access to the page and unlock it via a password. I am asking for help in creating or at least considering my proposal. If this plugin is available, I will not have to look for another CMS anymore

**Comment by ParitoshBh** [comment]
I am sorry but not really sure how this would tie in to this theme (or any other theme for that matter). I believe you are looking for a plugin with Wordpress style private posts.

This might be of some help - [Grav Plugin Login](https://github.com/getgrav/grav-plugin-login)

**Comment by bialy03** [comment]
And how would I try to import a gravity plugin into this CMS, could it work?

19.12.2018 3:57 AM "Paritosh Bhatia" <notifications@github.com> napisał(a):

**Comment by ParitoshBh** [comment]
I believe we are not on the same page, this theme is for Grav CMS and is just a theme. The base structure is provided by Grav CMS and as such, you should be able to install all plugins that are compatible with Grav CMS.

As for the ability of this theme to work with that plugin, I haven't tested that (in-fact I wasn't even aware of that plugin before this issue was created!). It would be great if you could try and use the plugin. If any issues come up, I'll try to get it fixed!

**Comment by bialy03** [comment]
I do not believe what I did. I mistook the repositories. I am sorry for the trouble. Yes it is like being sleepy.
